name = "MEDYANRegistry"
uuid = "cf97433f-abed-4a02-acf3-1c28d7c33f7f"
repo = "git@github.com:medyan-dev/MEDYANRegistry.git"

[packages]
d423b6e5-1c84-4ae2-8d2d-b903aee15ac7 = { name = "StorageTrees", path = "S/StorageTrees" }
